apiVersion: v1
kind: Service
metadata:
  name: starbucks-service
  labels:
    app: starbucks
    tier: frontend
spec:
  selector:
    app: starbucks
    tier: frontend
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer